# Generated by Django 5.1.4 on 2024-12-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('delivered', 'Livrée'), ('canceled', 'Annulée'), ('on-site', 'Sur place')], max_length=50),
        ),
    ]
