# Generated by Django 5.1.4 on 2024-12-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("izouapp", "0002_alter_deliveryperson_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "Livrée"),
                    ("canceled", "Annulée"),
                    ("on-site", "Sur place"),
                    ("pending", "En attente"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
