# Generated by Django 5.1.4 on 2024-12-30 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0003_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='onSiteHour',
            field=models.TimeField(default=datetime.time(13, 14, 39, 229610)),
        ),
    ]
