# Generated by Django 5.1.4 on 2024-12-31 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0004_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='onSiteHour',
            field=models.TimeField(default=datetime.time(11, 56, 41, 164234)),
        ),
    ]
