# Generated by Django 5.1.4 on 2024-12-31 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0005_notification_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='onSiteHour',
            field=models.TimeField(default=datetime.time(12, 43, 36, 77272)),
        ),
    ]
