# Generated by Django 5.1.4 on 2024-12-31 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0007_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='onSiteHour',
            field=models.TimeField(default=datetime.time(15, 19, 9, 735898)),
        ),
    ]
