# Generated by Django 5.1.4 on 2024-12-31 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0008_orders_notified_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='onSiteHour',
            field=models.TimeField(default=datetime.time(15, 31, 15, 640826)),
        ),
    ]
