# Generated by Django 5.1.4 on 2025-01-01 20:41

import izouapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0009_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='onSiteHour',
            field=models.TimeField(default=izouapp.models.get_current_time),
        ),
    ]
