# Generated by Django 5.1.4 on 2025-01-02 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0010_alter_orders_onsitehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
