# Generated by Django 5.1.4 on 2025-01-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izouapp', '0011_pizza_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_digest_sent', models.BooleanField(default=False)),
                ('monthly_digest_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
